### ISSUE TITLE
Missing use core::num::Float?

### ISSUE THREAD

**Issue by ezavod** [rust-lang-nursery/libm#149]
Can't compile with rustc 1.26.2 stable on OpenSUSE Tumbleweed 64bit because I get errors like:
```
error[E0599]: no function or associated item named `from_bits` found for type `f32` in the current scope
 --> libm/src/math/tanhf.rs:9:9
  |
9 |     x = f32::from_bits(ix);
  |         ^^^^^^^^^^^^^^ function or associated item not found in `f32`
  |
  = help: items from traits can only be used if the trait is in scope
  = note: the following trait is implemented but not in scope, perhaps add a `use` for it:
          candidate #1: `use core::num::Float;
```
Temporarily fixed by `use core::num::Float;`.

**Comment by HadrienG2** [comment]
Same issue here. I'm not sure why this happens though, as [these functions should](https://doc.rust-lang.org/std/primitive.f64.html#method.from_bits) [actually exist in std](https://doc.rust-lang.org/std/primitive.f32.html#method.from_bits), and there is no obvious reason why they should not exist in core.

Perhaps a rustc bug report is in order?

**Comment by HadrienG2** [comment]
Mmm... it does work with rustc 1.28 installed via rustup, so the problem seems to originate from either 1.26 or the Tumbleweed package. Let's investigate further...

**Comment by HadrienG2** [comment]
Alright, the Rust toolchain version is the issue. 1.26.2 installed via rustup doesn't work, 1.27.0 installed via rustup does work. The relevant functionality was likely introduced by [this PR](https://github.com/rust-lang/rust/pull/49896/) during the 1.27 release cycle.

So... I guess Tumbleweed users will need to use rustup for now if they want to use the libm crate or a crate that indirectly depends on it like nalgebra.

**Comment by ezavod** [comment]
@HadrienG2 Thanks for your investigation of this issue.
I also got it to work after fiddling around with different versions of the rust toolchain.

So I will leave this open for now and close it as soon as the working version landed officially.
