### ISSUE TITLE
libm-0.1.3 fails to build on stable Rust 1.31.0

### ISSUE THREAD

**Issue by eldruin** [rust-lang-nursery/libm#182]
libm 0.1.3 fails to build on stable Rust 1.31.0 with this error message:
```
error[E0658]: imports can only refer to extern crate names passed with `--extern` on stable channel (see issue #53130)
  --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/libm-0.1.3/src/lib.rs:23:9
   |
19 | mod math;
   | --------- not an extern crate passed with `--extern`
...
23 | pub use math::*;
   |         ^^^^
   |
note: this import refers to the module defined here
  --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/libm-0.1.3/src/lib.rs:19:1
   |
19 | mod math;
   | ^^^^^^^^^
                                                                                
error: aborting due to previous error
                                                                                
For more information about this error, try `rustc --explain E0658`.
error: Could not compile `libm`.
```
See the [CI job logfile here](https://travis-ci.org/eldruin/tmp006-rs/jobs/542282737)
Is there a minimum supported rust version policy for this crate?

**Comment by alexcrichton** [comment]
This crate only supports the latest stable for now, but if you would like to send a PR to fix that we could merge it!

**Comment by eldruin** [comment]
@alexcrichton is there a timeline for a new release? I can also contribute a PR updating the changelog and bumping the version if you want.

**Comment by alexcrichton** [comment]
That'd be great yeah, I can publish after merging
